version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app_nihad
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: final_project
#            MYSQL_USER: root
#            MYSQL_PASSWORD: laravel_password
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
