name: Update PR Description on Open or Sync

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  update-description:
    if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'alpha'
    runs-on: ubuntu-latest

    steps:
      - name: Update PR description
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const newBody = `This pull request is created from \`${pr.head.ref}\` to \`${pr.base.ref}\`.`;

            if (pr.body !== newBody) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                body: newBody,
              });
            }
